version: '1'

defaults:
  files:
    helpmd:
      path: files/help.md
  vars:
    base_img_reg: registry.fedoraproject.org/
    base_img_ns: f26-modular/
    base_img_name: boltron
    base_img_tag: latest

configurations:
  - name: nodejs-6
    image_name: modularitycontainers/nodejs:6
    vars:
      install_pkgs: nodejs-f26
      node_version: 6

  - name: nodejs-8
    image_name: modularitycontainers/nodejs:8
    vars:
      install_pkgs: nodejs-8
      node_version: 8
